# TCP
ATMOCUBE_IP = '192.168.1.82'
ATMOCUBE_IP_PORT = 502
LEVOIT_EMAIL = '[email]'
LEVOIT_PASSWORD = '[password]'
# RTU
ATMOCUBE_RTU_PORT = '/dev/cu.usbserial-AQ027VNZ'
ATMOCUBE_RTU_DEVICE_ID = 10
ATMOCUBE_RTU_BAUDRATE = 115200
ATMOCUBE_RTU_DATA_BITS = 8
ATMOCUBE_RTU_PARITY = 'N'
ATMOCUBE_RTU_STOP_BITS = 1 
# BLE
ATMOCUBE_BLE_NAME = 'CUBE_004C'